spring:
  application:
    name: cinetrack-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cinetrack}
    username: ${SPRING_DATASOURCE_USERNAME:cinetrack_user}
    password: ${SPRING_DATASOURCE_PASSWORD:cinetrack123}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        bytecode:
          use_reflection_optimizer: false
        enhancer:
          enableLazyInitialization: false
          enableDirtyTracking: false
          enableAssociationManagement: false
    show-sql: true
    
  security:
    user:
      name: admin
      password: admin
      
server:
  port: 8080
  servlet:
    context-path: /api

# JWT設定 (本番環境では必ずJWT_SECRET環境変数を設定してください)
jwt:
  secret: ${JWT_SECRET:cinetrack-jwt-secret-key-change-in-production-256-bits-required-abcdef123456}
  expiration: ${JWT_EXPIRATION:86400}

# TMDb API設定
tmdb:
  api-key: ${TMDB_API_KEY:demo_api_key_please_replace_with_actual_key}
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}
  
# CORS設定
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  
logging:
  level:
    com.cinetrack: DEBUG
    org.springframework.security: DEBUG