spring:
  application:
    name: cinetrack-backend-test
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
    
  h2:
    console:
      enabled: true
      
  security:
    user:
      name: admin
      password: admin

# JWT設定（テスト用）
jwt:
  secret: testSecretKeyForCineTrackApplicationMustBe256BitsLongForSecurityTest
  expiration: 3600

# TMDb API設定（テスト用）
tmdb:
  api-key: test_api_key
  base-url: http://localhost:8080/mock-tmdb
  
# CORS設定（テスト用）
cors:
  allowed-origins: http://localhost:3000
  
logging:
  level:
    com.cinetrack: WARN
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    root: WARN